version: '3.8'

services:
  gateway:
    build:
      context: ./nextGen-IGA-tool/gateway
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - ACCESS_MGMT_URL=http://access-management:3001
      - RECOMMENDATION_URL=http://recommendation:3002
      - NATS_URL=${NATS_URL:-nats://54.224.250.252:4222}
      - DB_HOST=${DB_HOST:-13.206.205.158}
      - DB_USER=${DB_USER:-abhik}
      - DB_PASSWORD=${DB_PASSWORD:-abhikSQL}
      - DB_NAME=${DB_NAME:-abhik_db}
      - EXTERNAL_AUTH_URL=${EXTERNAL_AUTH_URL:-http://18.60.129.12:8080}

  access-management:
    build:
      context: ./nextGen-IGA-tool/access-management
    restart: always
    ports:
      - "3001:3001"
    environment:
      - ACCESS_MGMT_PORT=3001
      - NATS_URL=${NATS_URL:-nats://54.224.250.252:4222}
      - DB_HOST=${DB_HOST:-13.206.205.158}
      - DB_USER=${DB_USER:-abhik}
      - DB_PASSWORD=${DB_PASSWORD:-abhikSQL}
      - DB_NAME=${DB_NAME:-abhik_db}

  event-manager:
    build:
      context: ./nextGen-IGA-tool/event-manager
    restart: always
    environment:
      - NATS_URL=${NATS_URL:-nats://54.224.250.252:4222}

  notifications:
    build:
      context: ./nextGen-IGA-tool/notifications
    restart: always
    environment:
      - NATS_URL=${NATS_URL:-nats://54.224.250.252:4222}
      - DB_HOST=${DB_HOST:-13.206.205.158}
      - DB_USER=${DB_USER:-abhik}
      - DB_PASSWORD=${DB_PASSWORD:-abhikSQL}
      - DB_NAME=${DB_NAME:-abhik_db}

  recommendation:
    build:
      context: ./nextGen-IGA-tool/recommendation
    restart: always
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - NATS_URL=${NATS_URL:-nats://54.224.250.252:4222}
      - DB_HOST=${DB_HOST:-13.206.205.158}
      - DB_USER=${DB_USER:-abhik}
      - DB_PASSWORD=${DB_PASSWORD:-abhikSQL}
      - DB_NAME=${DB_NAME:-abhik_db}

  frontend:
    build:
      context: ./nextgen-iga-frontend
    restart: always
    ports:
      - "80:80"
    environment:
      - VITE_API_BASE_URL=http://${PUBLIC_IP:-localhost}:3000
    depends_on:
      - gateway
