/**
 * Standard payload schemas (JSDoc only – no runtime cost).
 *
 * Every message on the bus uses GatewayEnvelope.
 * Each service returns ServiceReply for sync calls.
 */

/**
 * @typedef {Object} GatewayEnvelope
 * @property {string} requestId    - UUID generated by the gateway per HTTP request
 * @property {string} userId       - from X-User-ID header (injected by gateway after JWT validation)
 * @property {string} role         - from X-Role header
 * @property {string} method       - HTTP method (GET | POST | PUT | DELETE | PATCH)
 * @property {string} path         - Original HTTP path, e.g. /api/user/login
 * @property {Object} body         - Parsed request body
 * @property {Object} query        - URL query params
 * @property {Object} params       - Path params extracted by express
 * @property {number} timestamp    - epoch ms
 */

/**
 * @typedef {Object} ServiceReply
 * @property {boolean} ok
 * @property {number}  status      - HTTP-equivalent status code
 * @property {string}  message
 * @property {Object}  [data]
 * @property {string}  [error]
 */

/**
 * @typedef {Object} NotifyEnvelope
 * @property {string} userId
 * @property {string} event        - e.g. "audit.report.ready"
 * @property {Object} payload
 * @property {number} timestamp
 */

export const SCHEMAS = {
  GatewayEnvelope: "see JSDoc above",
  ServiceReply: "see JSDoc above",
  NotifyEnvelope: "see JSDoc above",
};
